_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 81
                - 102
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 81
                - 102
            "3":
                - 2
                - 3
                - 8
                - 13
                - 23
                - 55
                - 62
            "4": 3.8.19
            "5": 0.18.3
            "8":
                - 1
                - 5
            "10":
                - 17
            "12": 0.18.3
            "13": darwin-arm64
